const express = require('express')
const router = express.Router()
const StaffController = require('../Apps/Controllers/Staff.controller')

router.route('/')
    .get(StaffController.Page_Index)
router.route('/profile')
    .get(StaffController.Staff_Profile)
router.route('/PersonalSupport')
    .get(StaffController.Group_Page)
router.route('/PersonalSupport/CreateGroup')
    .get(StaffController.Get_Create_Group)
    .post(StaffController.Post_Create_Group)
router.route('/PersonalSupport/GroupDetail/:group_id')
    .get(StaffController.Get_Group_Detail)
router.route('/PersonalSupport/UpdateGroup/:group_id')
    .get(StaffController.Get_Update_Group)
    .post(StaffController.Post_Update_Group)
router.route('/PersonalSupport/DeleteGroup/:group_id')
    .get(StaffController.Get_Delete_Group)
router.route('/PersonalSupport/Group/:group_id/AddStudent/:role_id')
    .get(StaffController.Get_List_Student)
router.route('/PersonalSupport/Group/:group_id/AddStudent/:role_id/:student_id')
    .get(StaffController.Add_To_ListStudent)
router.route('/PersonalSupport/Group/:group_id/ListAddStudent/:role_id')
    .get(StaffController.Get_Add_Student)
    .post(StaffController.Post_Add_Student)
router.route('/PersonalSupport/Group/:group_id/ListAddStudent/:role_id/delete/:student_id')
    .get(StaffController.Delete_StudentInListAdd)
router.route('/PersonalSupport/GroupDetail/:group_id/DeleteStudentOfGroup/:student_id')
    .get(StaffController.Delete_Student_Of_Group)
router.route('/PersonalSupport/Group/:group_id/SendMail')
    .get(StaffController.Send_Mail_For_Group)
    .post(StaffController.Post_Send_Mail_For_Group)
router.route('/Account')
    .get(StaffController.Index_Account)
router.route('/Account/:role_id')
    .get(StaffController.List_Account)
router.route('/Account/:role_id/SendMail')
    .get(StaffController.Get_SendMail_For_Account)
    .post(StaffController.Post_SendMail_For_Account)
router.route('/Account/:role_id/Create')
    .get(StaffController.Get_Create_Account)
    .post(StaffController.Post_Create_Account)
router.route('/Account/:role_id/Detail/:user_id')
    .get(StaffController.Detail_Account)
router.route('/Account/:role_id/Update/:user_id')
    .get(StaffController.Get_Update_Account)
    .post(StaffController.Post_Update_Account)
router.route('/Account/:role_id/Delete/:user_id')
    .get(StaffController.Get_Delete_Account)
router.route('/Interactive')
    .get(StaffController.Chart)
router.route('/chart/:role_id')
    .get(StaffController.Chart_Role)
router.route('/DetailMessage/:user_id')
    .get(StaffController.Detail_Mess)
router.route('/StudentSupport')
    .get(StaffController.Student_Support)
router.route('/TutorChart')
    .get(StaffController.Chart_Personal_Tutor)
router.route('/TutorChart/:user_id')
    .get(StaffController.Detail_Personal_Tutor)

module.exports = router
